### ISSUE TITLE
Installing Speech Recognition using pip install SpeechRecognition ,  gave error 

### ISSUE THREAD

**Issue by Shraddhakh** [Shraddhakh/Micro-Projects#2]
(Jan) PS D:\Shraddha Projects\Jan\Jan\codes> python -m speech_recognition
Traceback (most recent call last):
  File "D:\Shraddha Projects\Jan\Jan\lib\site-packages\speech_recognition\__init__.py", line 108, in get_pyaudio
ModuleNotFoundError: No module named 'pyaudio'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\Shraddha Projects\Jan\Jan\lib\site-packages\speech_recognition\__main__.py", line 4, in <module>    
    m = sr.Microphone()
  File "D:\Shraddha Projects\Jan\Jan\lib\site-packages\speech_recognition\__init__.py", line 79, in __init__   
    self.pyaudio_module = self.get_pyaudio()
  File "D:\Shraddha Projects\Jan\Jan\lib\site-packages\speech_recognition\__init__.py", line 110, in get_pyaudio
    raise AttributeError("Could not find PyAudio; check installation")
AttributeError: Could not find PyAudio; check installation
![Screenshot (27)](https://user-images.githubusercontent.com/54411346/104524991-2278ea00-5664-11eb-9164-19415a457a7b.png)

**Comment by Shraddhakh** [comment]
Solved error using :
pip install pipwin
pipwin install pyaudio
then
pip install SpeechRecognition



![Screenshot (28)](https://user-images.githubusercontent.com/54411346/104525129-65d35880-5664-11eb-9820-301b9abff7af.png)
![Screenshot (29)](https://user-images.githubusercontent.com/54411346/104525136-6835b280-5664-11eb-82a4-f03c9dd8556f.png)
